### PR TITLE
Add tests against dockerd on the host system (k8s cordining/uncording not tested)

### LINKED ISSUE #16: Add tests
- We lack unit tests of the python code itself
- We lack a test to verify our built image will start
- We lack e2e tests

### PR DESCRIPTION
**Pull request by minrk**
started working on these, but it immediately became difficult to run tests locally because I haven't been able to get docker-in-docker to work with a mounted docker directory (presumably a docker-on-mac issue). Shouldn't be a problem on true linux, though.

closes #16

### CODE REVIEW

**Comment by consideRatio** [comment]
(Min I'm working this actively atm)

**Comment by consideRatio** [comment]
@minrk I couldn't stay away from the mystery, it was solved by replacing /dev/zero with /dev/urandom, use of nocache=True passed to the build also didn't do the trick.

- I've opened #123 as well, but it doesn't seem to me like a serious problem.

**Review by consideRatio — APPROVED** [review]
Pweh tests as passing and makes sense to me, feel free to go for a merge or push changes and then merge @minrk!

**Comment by minrk** [comment]
Wonderful!

**Pull request merged**
