### PR TITLE
Use tini in Dockerfile to react to SIGTERM properly

### PR DESCRIPTION
**Pull request by consideRatio**
A fix like the one discussed in https://github.com/2i2c-org/pilot-hubs/issues/443, based on https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/d3b314d6d297e134ac253c07ac5ee550baeff6b2/images/secret-sync/Dockerfile, that helps a `docker stop` or `kubectl delete` shut down the container directly instead of waiting the grace period for no use.

### CODE REVIEW

**Comment by yuvipanda** [comment]
I think it was necessary there because it was bash, and bash swallows signals. However, we are using a pure python script here - I don't think tini is necessary?

**Comment by consideRatio** [comment]
I verified it was needed locally using docker as described in the github issue, im not sure why.

**Comment by consideRatio** [comment]
Perhaps having the script as an executable via entry_points is making something different than just running `python script.py`?

**Comment by yuvipanda** [comment]
Hmm, that doesn't match my understanding so my understanding probably needs to change :D No harm in having tini on

**Pull request merged**
